data_source:
  base_url: "https://www.ncei.noaa.gov/data/local-climatological-data/access/"
  year: 2023
  output: /home/aravind/Documents/BDL_ASSGN_4/Climate_dataset{year}.html
  temp_dir: /home/aravind/Documents/BDL_ASSGN_4/data
  max_files: 10
  local: /home/aravind/Documents/BDL_ASSGN_4/

data_prepare:
  dest_folder: /home/aravind/Documents/BDL_ASSGN_4/prepare_data

data_process:
  dest_folder: /home/aravind/Documents/BDL_ASSGN_4/process_data

evaluate:
  output: /home/aravind/Documents/BDL_ASSGN_4/output

